/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisplaySlugRouteImport } from './routes/$displaySlug'
import { Route as IndexRouteImport } from './routes/index'

const DisplaySlugRoute = DisplaySlugRouteImport.update({
  id: '/$displaySlug',
  path: '/$displaySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$displaySlug': typeof DisplaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$displaySlug': typeof DisplaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$displaySlug': typeof DisplaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$displaySlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$displaySlug'
  id: '__root__' | '/' | '/$displaySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplaySlugRoute: typeof DisplaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$displaySlug': {
      id: '/$displaySlug'
      path: '/$displaySlug'
      fullPath: '/$displaySlug'
      preLoaderRoute: typeof DisplaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplaySlugRoute: DisplaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
