/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPlaylistsRouteImport } from './routes/admin.playlists'
import { Route as AdminDisplaysRouteImport } from './routes/admin.displays'
import { Route as AdminContentRouteImport } from './routes/admin.content'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisplaysRoute = AdminDisplaysRouteImport.update({
  id: '/displays',
  path: '/displays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/displays': typeof AdminDisplaysRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/displays': typeof AdminDisplaysRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/displays': typeof AdminDisplaysRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/content'
    | '/admin/displays'
    | '/admin/playlists'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/content'
    | '/admin/displays'
    | '/admin/playlists'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/content'
    | '/admin/displays'
    | '/admin/playlists'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/displays': {
      id: '/admin/displays'
      path: '/displays'
      fullPath: '/admin/displays'
      preLoaderRoute: typeof AdminDisplaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminDisplaysRoute: typeof AdminDisplaysRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminDisplaysRoute: AdminDisplaysRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
